version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_prisma
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db_testing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
